# TCL File Generated by Component Editor 18.1
# Thu May 11 14:09:56 CST 2023
# DO NOT MODIFY


# 
# ddr3_vga_top "ddr3_vga_top" v1.0
# zhangfeng 2023.05.11.14:09:56
# ddr3_vga_top
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_vga_top
# 
set_module_property DESCRIPTION ddr3_vga_top
set_module_property NAME ddr3_vga_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CoreCourse
set_module_property AUTHOR zhangfeng
set_module_property DISPLAY_NAME ddr3_vga_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr3_vga_top_me
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file burst_read_master.v VERILOG PATH ip/ddr3_vga/burst_read_master.v
add_fileset_file ddr3_read.v VERILOG PATH ip/ddr3_vga/ddr3_read.v
add_fileset_file ddr3_vga_ctrl.v VERILOG PATH ip/ddr3_vga/ddr3_vga_ctrl.v
add_fileset_file ddr3_vga_top.v VERILOG PATH ip/ddr3_vga/ddr3_vga_top.v TOP_LEVEL_FILE
add_fileset_file latency_aware_read_master.v VERILOG PATH ip/ddr3_vga/latency_aware_read_master.v
add_fileset_file vga_ctrl.v VERILOG PATH ip/ddr3_vga/vga_ctrl.v


# 
# parameters
# 
add_parameter USER_DATA_WIDTH INTEGER 128
set_parameter_property USER_DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property USER_DATA_WIDTH DISPLAY_NAME USER_DATA_WIDTH
set_parameter_property USER_DATA_WIDTH TYPE INTEGER
set_parameter_property USER_DATA_WIDTH UNITS None
set_parameter_property USER_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USER_DATA_WIDTH HDL_PARAMETER true
add_parameter AVALON_DATA_WIDTH INTEGER 128
set_parameter_property AVALON_DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property AVALON_DATA_WIDTH DISPLAY_NAME AVALON_DATA_WIDTH
set_parameter_property AVALON_DATA_WIDTH TYPE INTEGER
set_parameter_property AVALON_DATA_WIDTH UNITS None
set_parameter_property AVALON_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AVALON_DATA_WIDTH HDL_PARAMETER true
add_parameter MEMORY_BASED_FIFO INTEGER 1
set_parameter_property MEMORY_BASED_FIFO DEFAULT_VALUE 1
set_parameter_property MEMORY_BASED_FIFO DISPLAY_NAME MEMORY_BASED_FIFO
set_parameter_property MEMORY_BASED_FIFO TYPE INTEGER
set_parameter_property MEMORY_BASED_FIFO UNITS None
set_parameter_property MEMORY_BASED_FIFO ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MEMORY_BASED_FIFO HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 256
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 256
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter FIFO_DEPTH_LOG2 INTEGER 8
set_parameter_property FIFO_DEPTH_LOG2 DEFAULT_VALUE 8
set_parameter_property FIFO_DEPTH_LOG2 DISPLAY_NAME FIFO_DEPTH_LOG2
set_parameter_property FIFO_DEPTH_LOG2 TYPE INTEGER
set_parameter_property FIFO_DEPTH_LOG2 UNITS None
set_parameter_property FIFO_DEPTH_LOG2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH_LOG2 HDL_PARAMETER true
add_parameter ADDRESS_WIDTH INTEGER 32
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true
add_parameter BURST_CAPABLE INTEGER 1
set_parameter_property BURST_CAPABLE DEFAULT_VALUE 1
set_parameter_property BURST_CAPABLE DISPLAY_NAME BURST_CAPABLE
set_parameter_property BURST_CAPABLE TYPE INTEGER
set_parameter_property BURST_CAPABLE UNITS None
set_parameter_property BURST_CAPABLE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_CAPABLE HDL_PARAMETER true
add_parameter MAXIMUM_BURST_COUNT INTEGER 16
set_parameter_property MAXIMUM_BURST_COUNT DEFAULT_VALUE 16
set_parameter_property MAXIMUM_BURST_COUNT DISPLAY_NAME MAXIMUM_BURST_COUNT
set_parameter_property MAXIMUM_BURST_COUNT TYPE INTEGER
set_parameter_property MAXIMUM_BURST_COUNT UNITS None
set_parameter_property MAXIMUM_BURST_COUNT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAXIMUM_BURST_COUNT HDL_PARAMETER true
add_parameter BURST_COUNT_WIDTH INTEGER 5
set_parameter_property BURST_COUNT_WIDTH DEFAULT_VALUE 5
set_parameter_property BURST_COUNT_WIDTH DISPLAY_NAME BURST_COUNT_WIDTH
set_parameter_property BURST_COUNT_WIDTH TYPE INTEGER
set_parameter_property BURST_COUNT_WIDTH UNITS None
set_parameter_property BURST_COUNT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_COUNT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point as
# 
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as associatedClock clock
set_interface_property as associatedReset reset
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as maximumPendingWriteTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true
set_interface_property as EXPORT_OF ""
set_interface_property as PORT_NAME_MAP ""
set_interface_property as CMSIS_SVD_VARIABLES ""
set_interface_property as SVD_ADDRESS_GROUP ""

add_interface_port as as_address address Input 2
add_interface_port as as_write write Input 1
add_interface_port as as_writedata writedata Input 32
add_interface_port as as_read read Input 1
add_interface_port as as_readdata readdata Output 32
add_interface_port as chipselect chipselect Input 1
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output ADDRESS_WIDTH
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_byteenable byteenable Output AVALON_DATA_WIDTH/8
add_interface_port avalon_master master_readdata readdata Input AVALON_DATA_WIDTH
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_burstcount burstcount Output BURST_COUNT_WIDTH
add_interface_port avalon_master master_waitrequest waitrequest Input 1


# 
# connection point vga
# 
add_interface vga conduit end
set_interface_property vga associatedClock clock
set_interface_property vga associatedReset reset
set_interface_property vga ENABLED true
set_interface_property vga EXPORT_OF ""
set_interface_property vga PORT_NAME_MAP ""
set_interface_property vga CMSIS_SVD_VARIABLES ""
set_interface_property vga SVD_ADDRESS_GROUP ""

add_interface_port vga vga_vsync vga_vsync Output 1
add_interface_port vga vga_rgb vga_rgb Output 24
add_interface_port vga vga_hsync vga_hsync Output 1
add_interface_port vga vga_de vga_de Output 1
add_interface_port vga vga_clk vga_clk Output 1


# 
# connection point wire
# 
add_interface wire conduit end
set_interface_property wire associatedClock clock
set_interface_property wire associatedReset ""
set_interface_property wire ENABLED true
set_interface_property wire EXPORT_OF ""
set_interface_property wire PORT_NAME_MAP ""
set_interface_property wire CMSIS_SVD_VARIABLES ""
set_interface_property wire SVD_ADDRESS_GROUP ""

add_interface_port wire flag flag Output 1

